# test commit to check my local machine as runner
name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted #ubuntu-latest

    strategy:
      matrix:
        python-version: [3.14]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd action-test
        python -m pytest addition.py
